### ISSUE TITLE
 Cannot read properties of undefined (reading 'getUserMedia')

### ISSUE THREAD

**Issue by jainsourabh2** [B4PT0R/streamlit-mic-recorder#5]
I am getting the below error when I run it on localhost 

> MicRecorder.tsx:95 Uncaught TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at e.startRecording (MicRecorder.tsx:95:32)
    at e.onClick (MicRecorder.tsx:54:18)
    at Object.u (react-dom.production.min.js:14:84)
    at h (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at b (react-dom.production.min.js:15:72)
    at ut (react-dom.production.min.js:52:170)
    at ot (react-dom.production.min.js:51:255)
    at st (react-dom.production.min.js:52:334)
    at pt (react-dom.production.min.js:56:10)
    
On the server side the error is :

2023-12-27 10:29:52.006 ComponentRequestHandler: GET /home/sourabh/.local/lib/python3.9/site-packages/streamlit_mic_recorder/frontend/build/bootstrap.min.css.map read error
Traceback (most recent call last):
  File "/home/sourabh/.local/lib/python3.9/site-packages/streamlit/web/server/component_request_handler.py", line 55, in get
    with open(abspath, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sourabh/.local/lib/python3.9/site-packages/streamlit_mic_recorder/frontend/build/bootstrap.min.css.map'

**Comment by jainsourabh2** [comment]
Got it working! It was python environment issue.

**Comment by B4PT0R** [comment]
Hello,

Sorry to show up after the battle :)

Thank you for the feedback.

Given that you found the solution, would you mind giving a bit more details about what was causing the issue and how you fixed it. Could be helpful to document the issue for other users encountering the same problem.

Many thanks,

Have a nice Christmas/New Year time.

Cheers!

Baptiste

**Comment by AmineIzanami** [comment]
Thanks @B4PT0R  for the work, I have faced the same issue, the thing was related to how streamlit server the application, For security reasons, the getUserMedia() method is available only in secure contexts (HTTPS), so what fixed my issues is access it using localhost, not an IP address.

**Comment by B4PT0R** [comment]
Hello @AmineIzanami !
Ok, good to know.
Thank you for your feedback.
Cheers!
